name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    # https://github.com/purescript-contrib/setup-purescript

    steps:
    # https://github.com/cachix/install-nix-action
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --command 'spago --global-cache skip --config test.dhall test'

    # https://github.com/purescript-contrib/setup-purescript

    # - uses: actions/checkout@v2
    # - name: Set up a PureScript toolchain
    #   uses: purescript-contrib/setup-purescript@main
    #   with:
    #     purescript: "0.14.1"
    #     spago: "0.20.1"

#    - name: Cache PureScript dependencies
#      uses: actions/cache@v2
#      # This cache uses the .dhall files to know when it should reinstall
#      # and rebuild packages. It caches both the installed packages from
#      # the `.spago` directory and compilation artifacts from the `output`
#      # directory. When restored the compiler will rebuild any files that
#      # have changed. If you do not want to cache compiled output, remove
#      # the `output` path.
#      with:
#        key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
#        path: |
#          .spago

    # - run: spago -x test.dhall test